### ISSUE TITLE
Could not build the Admin UI

### ISSUE THREAD

**Issue by vbontoux** [aws-samples/aws-saas-factory-eks-saas-workshop#25]
Hi dear contributors !
I'm experiencing an issue while running the workshop at [Step 2 - Build and deploy Admin Site container image](https://catalog.us-east-1.prod.workshops.aws/workshops/e04c0885-830a-479b-844b-4c7af79697f8/en-US/lab-1/2-admin-site-container#step-2-build-and-deploy-admin-site-container-image).
The Angular build is failing.
See Attached File
[admin-web-build-failure-output.txt](https://github.com/aws-samples/aws-saas-factory-eks-saas-workshop/files/9404012/admin-web-build-failure-output.txt)
Thanks !

**Comment by tobuck-aws** [comment]
Hi Vincent, thanks for the note. I'll push a change that should fix it. The problem is with CoreUI's versioning. They made breaking changes but didn't update their major version. I can pin it to a version that does build, however. Please note, that moving forward we're going to jettison CoreUI and use our own, simpler UI, based on Angular Material. For a sneak peak, feel free to check out the `feature-workshop-prep` branch.

**Comment by tobuck-aws** [comment]
Fixed.

**Comment by vbontoux** [comment]
I can confirm this is fixed ! 
Thanks a lot Toby !
