### ISSUE TITLE
Codepipeline error in creating silo tenant

### ISSUE THREAD

**Issue by shahramjoon** [aws-samples/aws-saas-factory-eks-saas-workshop#68]
I am in step 10 in here https://catalog.us-east-1.prod.workshops.aws/workshops/e04c0885-830a-479b-844b-4c7af79697f8/en-US/lab-4/4-test-silo

I am creating a tenant with Premuim tier. 

in codepipeline eks-saas-tenant-onboarding-pipeline 

i am getting this error appearing  in build step of Code pipeline when i want to create a tenant with pemium tier to test the solo scenario

in my cloudformatino i don't see any stack called ClusterStack if below error means it is looking for it. 

[Container] 2022/12/28 22:35:36 Running command REGION=$(aws cloudformation describe-stacks --stack-name ClusterStack --query "Stacks[0].Outputs[?OutputKey=='AWSRegion'].OutputValue" --output text)
995 |  
996 | An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id ClusterStack does not exist
997 |  
998 | [Container] 2022/12/28 22:35:49 Command did not exit successfully REGION=$(aws cloudformation describe-stacks --stack-name ClusterStack --query "Stacks[0].Outputs[?OutputKey=='AWSRegion'].OutputValue" --output text) exit status 255
999 | [Container] 2022/12/28 22:35:49 Phase complete: POST_BUILD State: FAILED
1000 | [Container] 2022/12/28 22:35:49 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: REGION=$(aws cloudformation describe-stacks --stack-name ClusterStack --query "Stacks[0].Outputs[?OutputKey=='AWSRegion'].OutputValue" --output text). Reason: exit status 255
1001

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by shahramjoon** [comment]
also in my dynamodb. EKS-SaaS-Stack-Metadata
i only see an item for stackName = eks-saas

**Comment by tobuck-aws** [comment]
I'll take a look. Thanks for reporting!

**Comment by miguelvidex** [comment]
Same problem here. The only stacks available are:
RootStack
EksStack
CDKToolkit

**Comment by tobuck-aws** [comment]
Fixed. Thanks for reporting.

**Comment by shahramjoon** [comment]
Thanks for fixing the issue.

What step in the workshop do i need to execute to create the Clusterstack?

**Comment by tobuck-aws** [comment]
Unfortunately, it's one of the very first things you do when executing the "on your own" portion. [In this step](https://catalog.us-east-1.prod.workshops.aws/workshops/e04c0885-830a-479b-844b-4c7af79697f8/en-US/lab-0/2-on-your-own/8-create-cluster), we have you deploy the EKS cluster. The bug was that the stack that deployed the cluster was named incorrectly. I would delete all deployed stacks from your previous install and try again. Please also ensure you delete the following:
* Any Cognito userpool created as a result of onboarding
* Any DynamoDB table that wasn't deleted when you deleted the stacks
